let LIGAS = [
	{"liga":"ZA-ARG1","mitad":true,"mitadFavorito":true,"codigoWplay":19296},
	{"liga":"ZA-ARGC","mitad":false,"mitadFavorito":true,"codigoWplay":19572},
	{"liga":"ZA-BRA1","mitad":true,"mitadFavorito":true,"codigoWplay":19297},
	{"liga":"ZA-BRA2","mitad":true,"mitadFavorito":true,"codigoWplay":19393},
	{"liga":"BROR","mitad":false,"mitadFavorito":false,"codigoWplay":47888},
	{"liga":"BALAC","mitad":false,"mitadFavorito":false,"codigoWplay":60289},
	{"liga":"ZA-BRA20","mitad":false,"mitadFavorito":false,"codigoWplay":26866},
	{"liga":"ZA-COL1","mitad":true,"mitadFavorito":true,"codigoWplay":19311},
	{"liga":"ZA-COL2","mitad":false,"mitadFavorito":false,"codigoWplay":29812},
	{"liga":"ZA-ECU2","mitad":false,"mitadFavorito":false,"codigoWplay":30530},
	{"liga":"ESP2","mitad":true,"mitadFavorito":true,"codigoWplay":48352},
	{"liga":"ZA-ESTC","mitad":false,"mitadFavorito":true,"codigoWplay":19497},
	{"liga":"S-JAP1","mitad":true,"mitadFavorito":true,"codigoWplay":19378},
	{"liga":"ZA-PAR1","mitad":false,"mitadFavorito":true,"codigoWplay":19359},
]