let LIGAS = [
	{"liga":"ZA-BOL1","mitad":false,"mitadFavorito":false,"codigoWplay":19786},
	{"liga":"ZA-BRAC","mitad":false,"mitadFavorito":true,"codigoWplay":2434793},
	{"liga":"ZA-CHIC","mitad":false,"mitadFavorito":false,"codigoWplay":19799},
	{"liga":"ZA-COL1","mitad":true,"mitadFavorito":true,"codigoWplay":19311},
	{"liga":"ZF-COL","mitad":false,"mitadFavorito":false,"codigoWplay":48455},
	{"liga":"U-CHAMC","mitad":false,"mitadFavorito":true,"codigoWplay":61789},
	{"liga":"U-EUROQ","mitad":false,"mitadFavorito":true,"codigoWplay":61810},
	{"liga":"U-CONFC","mitad":false,"mitadFavorito":true,"codigoWplay":1431783},
	{"liga":"AMIE","codigoWplay":617783,"mitad":false,"mitadFavorito":true},
	{"liga":"AMIC","codigoWplay":20183,"mitad":false,"mitadFavorito":true},
	{"liga":"I-LEAC","mitad":true,"mitadFavorito":true,"codigoWplay":29935},
	{"liga":"YE-RUSC","mitad":false,"mitadFavorito":false,"codigoWplay":19467},
	{"liga":"ZA-VEN1","mitad":false,"mitadFavorito":false,"codigoWplay":20080},
]