let LIGAS = [
	{"liga":"ZA-ARGC","mitad":false,"mitadFavorito":true,"codigoWplay":19572},
	{"liga":"ZA-BOL1","mitad":false,"mitadFavorito":false,"codigoWplay":19786},
	{"liga":"ZA-BRA20","mitad":false,"mitadFavorito":false,"codigoWplay":26866},
	{"liga":"ZA-CHIC","mitad":false,"mitadFavorito":false,"codigoWplay":19799},
	{"liga":"ZA-COL2","mitad":false,"mitadFavorito":false,"codigoWplay":29812},
	{"liga":"ZA-ECU2","mitad":false,"mitadFavorito":false,"codigoWplay":30530},
	{"liga":"R-ING1","mitad":true,"mitadFavorito":true,"codigoWplay":19157},
	{"liga":"ZA-MEX2","mitad":true,"mitadFavorito":true,"codigoWplay":61826},
	{"liga":"YE-PORT","mitad":false,"mitadFavorito":true,"codigoWplay":19382},
	{"liga":"ZA-LIBE","mitad":true,"mitadFavorito":true,"codigoWplay":19462},
	{"liga":"ZA-SUDA","mitad":false,"mitadFavorito":true,"codigoWplay":19348},
	{"liga":"YE-SUI1","mitad":true,"mitadFavorito":true,"codigoWplay":19305},
	{"liga":"YE-TURC","mitad":false,"mitadFavorito":false,"codigoWplay":19447},
]