let PARTIDOS_OPTIMIZADOS = [
	{"hora":11830,"liga":"ZA-ESTC","mitad":false,"mitadFavorito":true,"codigoWplay":19497,"local":"Orlando City","visitante":"Atlanta Utd","cuotaLocal":1,"empate":1,"cuotaVisitante":1,"cantidadDeApuestas":0,"cuotaCualquiera":1,"ambosAnotan":1,"over":1,"cuotaFavorito":1,"rate":1,"stake":0},
	{"hora":11900,"liga":"ZA-ESTC","mitad":false,"mitadFavorito":true,"codigoWplay":19497,"local":"St. Louis City","visitante":"Houston Dynamo","cuotaLocal":1,"empate":1,"cuotaVisitante":1,"cantidadDeApuestas":0,"cuotaCualquiera":1,"ambosAnotan":1,"over":1,"cuotaFavorito":1,"rate":1,"stake":0},
	{"hora":11900,"liga":"ZA-LIBE","mitad":true,"mitadFavorito":true,"codigoWplay":19462,"local":"Always Ready (Bol)","visitante":"Mirassol (Bra)","cuotaLocal":1,"empate":1,"cuotaVisitante":1,"cantidadDeApuestas":0,"cuotaCualquiera":1,"ambosAnotan":1,"over":1,"cuotaFavorito":1,"rate":1,"stake":0},
	{"hora":11900,"liga":"ZA-LIBE","mitad":true,"mitadFavorito":true,"codigoWplay":19462,"local":"Ind. Santa Fe (Col)","visitante":"Platense (Arg)","cuotaLocal":1,"empate":1,"cuotaVisitante":1,"cantidadDeApuestas":0,"cuotaCualquiera":1,"ambosAnotan":1,"over":1,"cuotaFavorito":1,"rate":1,"stake":0},
	{"hora":11930,"liga":"ZA-LIBE","mitad":true,"mitadFavorito":true,"codigoWplay":19462,"local":"Boca Jrs. (Arg)","visitante":"Cruzeiro (Bra)","cuotaLocal":1,"empate":1,"cuotaVisitante":1,"cantidadDeApuestas":0,"cuotaCualquiera":1,"ambosAnotan":1,"over":1,"cuotaFavorito":1,"rate":1,"stake":0},
	{"hora":11930,"liga":"ZA-SUDA","mitad":false,"mitadFavorito":true,"codigoWplay":19348,"local":"Sao Paulo (Bra)","visitante":"Millonarios (Col)","cuotaLocal":1,"empate":1,"cuotaVisitante":1,"cantidadDeApuestas":0,"cuotaCualquiera":1,"ambosAnotan":1,"over":1,"cuotaFavorito":1,"rate":1,"stake":0},
	{"hora":12100,"liga":"ZA-LIBE","mitad":true,"mitadFavorito":true,"codigoWplay":19462,"local":"Ind. del Valle (Ecu)","visitante":"Libertad (Par)","cuotaLocal":1,"empate":1,"cuotaVisitante":1,"cantidadDeApuestas":0,"cuotaCualquiera":1,"ambosAnotan":1,"over":1,"cuotaFavorito":1,"rate":1,"stake":0},
	{"hora":12100,"liga":"ZA-SUDA","mitad":false,"mitadFavorito":true,"codigoWplay":19348,"local":"América de Cali (Col)","visitante":"Tigre (Arg)","cuotaLocal":1,"empate":1,"cuotaVisitante":1,"cantidadDeApuestas":0,"cuotaCualquiera":1,"ambosAnotan":1,"over":1,"cuotaFavorito":1,"rate":1,"stake":0},
	{"hora":12100,"liga":"ZA-SUDA","mitad":false,"mitadFavorito":true,"codigoWplay":19348,"local":"Dep. Cuenca (Ecu)","visitante":"Recoleta (Par)","cuotaLocal":1,"empate":1,"cuotaVisitante":1,"cantidadDeApuestas":0,"cuotaCualquiera":1,"ambosAnotan":1,"over":1,"cuotaFavorito":1,"rate":1,"stake":0},
]