let PARTIDOS_OPTIMIZADOS = [
	{"hora":11630,"liga":"ZA-BOL1","mitad":false,"mitadFavorito":false,"codigoWplay":19786,"local":"Universitario de Vinto","visitante":"Guabira","cuotaLocal":1.48,"empate":4,"cuotaVisitante":5.75,"cantidadDeApuestas":38,"cuotaCualquiera":1.333,"ambosAnotan":1.8,"over":1.727,"cuotaFavorito":1,"rate":1,"stake":0,"localMitad":1,"visitanteMitad":1,"favorito":""},
	{"hora":11700,"liga":"ZA-ARG1","mitad":true,"mitadFavorito":true,"codigoWplay":19296,"local":"San Lorenzo","visitante":"CA Belgrano","cuotaLocal":2.25,"empate":2.85,"cuotaVisitante":3.8,"cantidadDeApuestas":183,"cuotaCualquiera":1.7,"ambosAnotan":2.4,"over":3.1,"cuotaFavorito":2.375,"rate":1,"stake":0,"localMitad":2.375,"visitanteMitad":3.1,"favorito":"local"},
	{"hora":11730,"liga":"ZA-PAR1","mitad":false,"mitadFavorito":true,"codigoWplay":19359,"local":"Sol de America","visitante":"Sportivo Ameliano","cuotaLocal":2.4,"empate":3,"cuotaVisitante":2.95,"cantidadDeApuestas":88,"cuotaCualquiera":1.571,"ambosAnotan":2,"over":2.5,"cuotaFavorito":2.55,"rate":1,"stake":0,"localMitad":2.35,"visitanteMitad":2.55,"favorito":"visitante"},
	{"hora":11730,"liga":"ZA-PAR1","mitad":false,"mitadFavorito":true,"codigoWplay":19359,"local":"Club General Caballero JLM","visitante":"CS 2 de Mayo","cuotaLocal":3.1,"empate":3,"cuotaVisitante":2.3,"cantidadDeApuestas":89,"cuotaCualquiera":1,"ambosAnotan":1,"over":1,"cuotaFavorito":1,"rate":1,"stake":0,"localMitad":1,"visitanteMitad":1,"favorito":""},
	{"hora":11730,"liga":"ZA-PAR1","mitad":false,"mitadFavorito":true,"codigoWplay":19359,"local":"Nacional Asuncion","visitante":"Guarani Asuncion","cuotaLocal":2.4,"empate":3.1,"cuotaVisitante":2.85,"cantidadDeApuestas":90,"cuotaCualquiera":1.45,"ambosAnotan":1.8,"over":2.1,"cuotaFavorito":2.3,"rate":1,"stake":0,"localMitad":2.15,"visitanteMitad":2.3,"favorito":"visitante"},
	{"hora":11830,"liga":"ZA-COL1","mitad":true,"mitadFavorito":true,"codigoWplay":19311,"local":"Deportivo Pasto","visitante":"Independiente Santa Fe","cuotaLocal":2.65,"empate":2.95,"cuotaVisitante":3.1,"cantidadDeApuestas":171,"cuotaCualquiera":1.615,"ambosAnotan":2.1,"over":2.7,"cuotaFavorito":2.4,"rate":1,"stake":0,"localMitad":2.4,"visitanteMitad":2.6,"favorito":"local"},
	{"hora":11900,"liga":"ZA-ARG1","mitad":true,"mitadFavorito":true,"codigoWplay":19296,"local":"Estudiantes de La Plata","visitante":"River Plate","cuotaLocal":3.55,"empate":3.1,"cuotaVisitante":2.2,"cantidadDeApuestas":188,"cuotaCualquiera":1.55,"ambosAnotan":2.05,"over":2.5,"cuotaFavorito":2.15,"rate":1,"stake":0,"localMitad":2.75,"visitanteMitad":2.15,"favorito":"visitante"},
	{"hora":12030,"liga":"ZA-COL1","mitad":true,"mitadFavorito":true,"codigoWplay":19311,"local":"Millonarios","visitante":"Atlético Nacional","cuotaLocal":1.8,"empate":3.5,"cuotaVisitante":5,"cantidadDeApuestas":165,"cuotaCualquiera":1.48,"ambosAnotan":2.1,"over":2.3,"cuotaFavorito":3,"rate":1,"stake":0,"localMitad":1.9,"visitanteMitad":3,"favorito":"visitante"},
]