let PARTIDOS_OPTIMIZADOS = [
	{"hora":11730,"liga":"BGOI","mitad":false,"mitadFavorito":false,"codigoWplay":"19789","local":"Anapolina","visitante":"Aparecidense","cuotaLocal":1,"empate":1,"cuotaVisitante":1,"cantidadDeApuestas":0,"cuotaCualquiera":1,"ambosAnotan":1,"over":1,"cuotaFavorito":1,"rate":1,"stake":0},
	{"hora":11730,"liga":"BGOI","mitad":false,"mitadFavorito":false,"codigoWplay":"19789","local":"Ouvidorense","visitante":"Anapolis","cuotaLocal":1,"empate":1,"cuotaVisitante":1,"cantidadDeApuestas":0,"cuotaCualquiera":1,"ambosAnotan":1,"over":1,"cuotaFavorito":1,"rate":1,"stake":0},
	{"hora":11745,"liga":"ZA-ARG1","mitad":true,"mitadFavorito":true,"codigoWplay":19296,"local":"Defensa y Justicia","visitante":"Estudiantes L.P.","cuotaLocal":1,"empate":1,"cuotaVisitante":1,"cantidadDeApuestas":0,"cuotaCualquiera":1,"ambosAnotan":1,"over":1,"cuotaFavorito":1,"rate":1,"stake":0},
	{"hora":11745,"liga":"ZA-ARG1","mitad":true,"mitadFavorito":true,"codigoWplay":19296,"local":"Tigre","visitante":"Racing Club","cuotaLocal":1,"empate":1,"cuotaVisitante":1,"cantidadDeApuestas":0,"cuotaCualquiera":1,"ambosAnotan":1,"over":1,"cuotaFavorito":1,"rate":1,"stake":0},
	{"hora":11800,"liga":"BCAR","mitad":false,"mitadFavorito":true,"codigoWplay":"19456","local":"Madureira","visitante":"Vasco","cuotaLocal":1,"empate":1,"cuotaVisitante":1,"cantidadDeApuestas":0,"cuotaCualquiera":1,"ambosAnotan":1,"over":1,"cuotaFavorito":1,"rate":1,"stake":0},
	{"hora":11800,"liga":"BPAU2","mitad":false,"mitadFavorito":false,"codigoWplay":"890797","local":"Piracicaba","visitante":"Monte Azul","cuotaLocal":1,"empate":1,"cuotaVisitante":1,"cantidadDeApuestas":0,"cuotaCualquiera":1,"ambosAnotan":1,"over":1,"cuotaFavorito":1,"rate":1,"stake":0},
	{"hora":11815,"liga":"ZA-PAR1","mitad":false,"mitadFavorito":true,"codigoWplay":19359,"local":"Cerro Porteño","visitante":"Sp. Luqueño","cuotaLocal":1,"empate":1,"cuotaVisitante":1,"cantidadDeApuestas":0,"cuotaCualquiera":1,"ambosAnotan":1,"over":1,"cuotaFavorito":1,"rate":1,"stake":0},
	{"hora":11820,"liga":"ZA-COL1","mitad":true,"mitadFavorito":true,"codigoWplay":19311,"local":"Inter Bogotá","visitante":"Tolima","cuotaLocal":1,"empate":1,"cuotaVisitante":1,"cantidadDeApuestas":0,"cuotaCualquiera":1,"ambosAnotan":1,"over":1,"cuotaFavorito":1,"rate":1,"stake":0},
	{"hora":11830,"liga":"ZA-CHI1","mitad":false,"mitadFavorito":true,"codigoWplay":19303,"local":"O'Higgins","visitante":"Dep. Concepción","cuotaLocal":1,"empate":1,"cuotaVisitante":1,"cantidadDeApuestas":0,"cuotaCualquiera":1,"ambosAnotan":1,"over":1,"cuotaFavorito":1,"rate":1,"stake":0},
	{"hora":12000,"liga":"ZA-ARG1","mitad":true,"mitadFavorito":true,"codigoWplay":19296,"local":"Argentinos Jrs.","visitante":"Belgrano","cuotaLocal":1,"empate":1,"cuotaVisitante":1,"cantidadDeApuestas":0,"cuotaCualquiera":1,"ambosAnotan":1,"over":1,"cuotaFavorito":1,"rate":1,"stake":0},
	{"hora":12000,"liga":"ZA-ARG1","mitad":true,"mitadFavorito":true,"codigoWplay":19296,"local":"Unión Santa Fe","visitante":"Gimnasia Mendoza","cuotaLocal":1,"empate":1,"cuotaVisitante":1,"cantidadDeApuestas":0,"cuotaCualquiera":1,"ambosAnotan":1,"over":1,"cuotaFavorito":1,"rate":1,"stake":0},
	{"hora":12030,"liga":"ZA-COL1","mitad":true,"mitadFavorito":true,"codigoWplay":19311,"local":"Pereira","visitante":"Junior","cuotaLocal":1,"empate":1,"cuotaVisitante":1,"cantidadDeApuestas":0,"cuotaCualquiera":1,"ambosAnotan":1,"over":1,"cuotaFavorito":1,"rate":1,"stake":0},
]