let PARTIDOS_OPTIMIZADOS = [
	{"hora":11915,"liga":"ZA-ARG1","mitad":true,"mitadFavorito":true,"codigoWplay":19296,"local":"Atl. Tucumán","visitante":"Atl. Tucumán","cuotaLocal":1,"empate":1,"cuotaVisitante":1,"cantidadDeApuestas":0,"cuotaCualquiera":1,"ambosAnotan":1,"over":1,"cuotaFavorito":1,"rate":1,"stake":0},
	{"hora":11915,"liga":"ZA-ARG1","mitad":true,"mitadFavorito":true,"codigoWplay":19296,"local":"Talleres","visitante":"Talleres","cuotaLocal":1,"empate":1,"cuotaVisitante":1,"cantidadDeApuestas":0,"cuotaCualquiera":1,"ambosAnotan":1,"over":1,"cuotaFavorito":1,"rate":1,"stake":0},
	{"hora":11830,"liga":"ZA-BOL1","mitad":false,"mitadFavorito":false,"codigoWplay":19786,"local":"Wilstermann","visitante":"Wilstermann","cuotaLocal":1,"empate":1,"cuotaVisitante":1,"cantidadDeApuestas":0,"cuotaCualquiera":1,"ambosAnotan":1,"over":1,"cuotaFavorito":1,"rate":1,"stake":0},
	{"hora":11820,"liga":"ZA-COL1","mitad":true,"mitadFavorito":true,"codigoWplay":19311,"local":"Junior","visitante":"Junior","cuotaLocal":1,"empate":1,"cuotaVisitante":1,"cantidadDeApuestas":0,"cuotaCualquiera":1,"ambosAnotan":1,"over":1,"cuotaFavorito":1,"rate":1,"stake":0},
	{"hora":11830,"liga":"ZA-EST1","mitad":true,"mitadFavorito":true,"codigoWplay":19302,"local":"Orlando City","visitante":"Orlando City","cuotaLocal":1,"empate":1,"cuotaVisitante":1,"cantidadDeApuestas":0,"cuotaCualquiera":1,"ambosAnotan":1,"over":1,"cuotaFavorito":1,"rate":1,"stake":0},
	{"hora":12045,"liga":"ZA-EST1","mitad":true,"mitadFavorito":true,"codigoWplay":19302,"local":"Los Angeles FC","visitante":"Los Angeles FC","cuotaLocal":1,"empate":1,"cuotaVisitante":1,"cantidadDeApuestas":0,"cuotaCualquiera":1,"ambosAnotan":1,"over":1,"cuotaFavorito":1,"rate":1,"stake":0},
	{"hora":11900,"liga":"ZA-MEX1","mitad":true,"mitadFavorito":true,"codigoWplay":19329,"local":"Necaxa","visitante":"Necaxa","cuotaLocal":1,"empate":1,"cuotaVisitante":1,"cantidadDeApuestas":0,"cuotaCualquiera":1,"ambosAnotan":1,"over":1,"cuotaFavorito":1,"rate":1,"stake":0},
	{"hora":11906,"liga":"ZA-MEX1","mitad":true,"mitadFavorito":true,"codigoWplay":19329,"local":"Juárez","visitante":"Juárez","cuotaLocal":1,"empate":1,"cuotaVisitante":1,"cantidadDeApuestas":0,"cuotaCualquiera":1,"ambosAnotan":1,"over":1,"cuotaFavorito":1,"rate":1,"stake":0},
	{"hora":12105,"liga":"ZA-MEX1","mitad":true,"mitadFavorito":true,"codigoWplay":19329,"local":"Club América","visitante":"Club América","cuotaLocal":1,"empate":1,"cuotaVisitante":1,"cantidadDeApuestas":0,"cuotaCualquiera":1,"ambosAnotan":1,"over":1,"cuotaFavorito":1,"rate":1,"stake":0},
	{"hora":11800,"liga":"ZA-PER1","mitad":false,"mitadFavorito":false,"codigoWplay":19340,"local":"Universitario","visitante":"Universitario","cuotaLocal":1,"empate":1,"cuotaVisitante":1,"cantidadDeApuestas":0,"cuotaCualquiera":1,"ambosAnotan":1,"over":1,"cuotaFavorito":1,"rate":1,"stake":0},
	{"hora":11830,"liga":"ZA-VEN1","mitad":false,"mitadFavorito":false,"codigoWplay":20080,"local":"La Guaira","visitante":"La Guaira","cuotaLocal":1,"empate":1,"cuotaVisitante":1,"cantidadDeApuestas":0,"cuotaCualquiera":1,"ambosAnotan":1,"over":1,"cuotaFavorito":1,"rate":1,"stake":0},
]